{% set version = "0.4.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-egg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/egg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/egg/egg_{{ version }}.tar.gz
  sha256: 15c8ba7cf2676eb0460de7e5dfbc89fc3175ac22a8869cfd44d66d156fd6c7bb

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ggplot2
    - r-gridextra >=2.3
    - r-gtable
  run:
    - r-base
    - r-ggplot2
    - r-gridextra >=2.3
    - r-gtable

test:
  commands:
    - $R -e "library('egg')"           # [not win]
    - "\"%R%\" -e \"library('egg')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=egg
  license: GPL-3
  summary: Miscellaneous functions to help customise 'ggplot2' objects. High-level functions
    are provided to post-process 'ggplot2' layouts and allow alignment between plot
    panels, as well as setting panel sizes to fixed values. Other functions include
    a custom 'geom', and helper functions to enforce symmetric scales or add tags to
    facetted plots.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: egg
# Type: Package
# Title: Extensions for 'ggplot2': Custom Geom, Plot Alignment, Symmetrised Scale, and Fixed Panel Size
# Version: 0.4.2
# Authors@R: c(person("Baptiste", "Auguie", email = "baptiste.auguie@gmail.com", role = c("aut", "cre")))
# License: GPL-3
# Description: Miscellaneous functions to help customise 'ggplot2' objects. High-level functions are provided to post-process 'ggplot2' layouts and allow alignment between plot panels, as well as setting panel sizes to fixed values. Other functions include a custom 'geom', and helper functions to enforce symmetric scales or add tags to facetted plots.
# VignetteBuilder: knitr
# Depends: gridExtra (>= 2.3), ggplot2
# Imports: gtable, grid, grDevices, stats, utils
# Suggests: knitr, png
# RoxygenNote: 6.1.0
# NeedsCompilation: no
# Packaged: 2018-11-02 23:59:07 UTC; baptiste
# Author: Baptiste Auguie [aut, cre]
# Maintainer: Baptiste Auguie <baptiste.auguie@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-11-03 05:20:28 UTC
