travis:
  secure:
    BINSTAR_TOKEN: It9PNI06iuMKqSPJLDCfXfS8EO581WXAZqyuf78+QDIui0NK9dOo6eO06A89bBqAQ5AYTVHL3rNO7c9teh5aZQUXNAcrtLQ4WDy7ZkcGuPlPg/tbWke39kSQhBDqWKVaGcHN56xK4a1aRtVUiZUZajzxcGQIVs68CU8NW2KY5YAmDnjpkYb33ONwKA8hD7OleKkc7e/A8MhdBP1UYnGmaflpbSR2pGWwOC2ht9ZEyGqG8dc1K1xON5cN9NyAKvjtDw+AwBwz1APBx5vHmkCFyLm3MfGFNwNMDZFRTVuxoAi+V18GFN1ZUlSqBgeHl8uHfgeFwDVAOtF241k+5WZysN0JlaaP+jhW0tToT77Cm8q0rPxMBC3Mg5nl2IVfatQ/a5l2ok3kWN7XlrJ+YPDVNMzqG0ghfjGYMsT6R31wYdKVC6UHamSZ2Q2JWHY9TF+fuJ2vLF2GjLk51w5BHcTAHL/Ny0foLA2KRIGs3kO1R0cRQVTCwTyXwDJe4cpqiycyOlzqlSUSovs0gGKIn/sGgU8ClzFIHwsarWj+KkzrXhbm2fyVTkl3MBGpivGlmwIcGGNgAWty0dYn1AzE2iPEUq4a1qCdPkSce1uKLp6w7dnE7mzelD1vhpNqTAz3MPjLHsttTTIIXKKQFvNhiWr1BMJSeqSV4G0Iamn6v91rABo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
