appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: pQPNM0SHk3K8d2dg018knkuJqgcmM1Ca8Ylq41/vdkXGJaZi5TUUUVgKSQK+f0shlO5H7P2/I4lXTEf9E9xpLi5MbWT5gzDxyRiGp8Mp4FB+F3iKx3rQhJCfhhRLjc3krOTHIiZS4WQ76ZddhOheHsViB2HynoP4o6gdBk6dxTgwkiFTz9Tg5XTOZdm/aZFh4egbM9UiMCWHmTns3k00gO8HR5Javk6hxdhlqpl+T7umq3O8Fqk9Kbv6Tum2Oj+CzgBiItZ66xSfc00DDflQvhLZ8E63PSBvhoOSe5QCscxUsta5w+8vF5NQhxFkPiP6MHZmbtG1AjhB5n/tP+4LloBfg6KlsJlyP8iElaCZKkuE9HnXKE4BlWGtUIQ8xmk2+mbNk/myjeGyJOKESjM0LeCYI1o/a2LlL3eUsuYNt8MaUlS5yFFE6byUy49G7EZwPJdkVu7inGMZuVwXBZflzeZpfimLW1nsj/A1Z3Do3jYpKNd4FaEvh9hcjtF6IT61s/3xxCjK68MJztv6ACenhJfsNA51nuSNtffNakHHDJOkTUgVEGZvkUj0YpiPeezrSHYHNYUAyzWNVrnpMvegDTTPmImi3ZKOWkNFxaapzIklWM+rymxX4h6HUHqkX0qoCr8UoG/ikfj8IdTe8GUohDMpcQGnyMTP4kCeRzbsAyc=
conda_forge_output_validation: true
